from .models import EsxiBuildSpec


def build_kickstart(spec: EsxiBuildSpec) -> str:
    dns = ",".join(spec.dns_servers)
    lines = [
        "# Generated by lab-builder",
        "vmaccepteula",
        f"rootpw {spec.root_password}",
        "install --firstdisk --overwritevmfs",
        f"network --bootproto=static --ip={spec.management_ip} --netmask={spec.subnet_mask} --gateway={spec.gateway} --nameserver={dns} --hostname={spec.hostname}",
        "reboot",
        "",
        "%firstboot --interpreter=busybox",
    ]
    if spec.enable_ssh:
        lines.append("vim-cmd hostsvc/enable_ssh")
        lines.append("vim-cmd hostsvc/start_ssh")
    if spec.disable_ipv6:
        lines.append("esxcli network ip set --ipv6-enabled=false || true")
    if spec.ntp_server:
        lines.append(f"esxcli system ntp set --server '{spec.ntp_server}' || true")
    lines.append("%end")
    return "\n".join(lines) + "\n"
