from shlex import quote

from .models import EsxiBuildSpec


def build_kickstart(spec: EsxiBuildSpec, esxi_version: str | None = None) -> str:
    esxi_version = str(esxi_version or getattr(spec, "esxi_version", "7") or "7").strip()
    dns = ",".join(spec.dns_servers)
    network_parts = [
        "network",
        "--bootproto=static",
        "--device=vmnic0",
        f"--ip={spec.management_ip}",
        f"--netmask={spec.subnet_mask}",
        f"--gateway={spec.gateway}",
        f"--nameserver={dns}",
        f"--hostname={spec.hostname}",
        "--addvmportgroup=0",
    ]
    if spec.vlan_id:
        network_parts.append(f"--vlanid={spec.vlan_id}")
    lines = [
        f"# Generated by lab-builder for ESXi {esxi_version}",
        "vmaccepteula",
        f"rootpw {spec.root_password}",
        "install --firstdisk --overwritevmfs",
        " ".join(network_parts),
        "reboot",
        "",
        "%firstboot --interpreter=busybox",
        "# vmnic numbering can differ by HPE model/firmware; repair management to the first linked NIC.",
        "LOG=/var/log/lab-builder-firstboot.log",
        "echo 'Lab Builder first boot network check' > $LOG",
        "esxcli network nic list >> $LOG 2>&1 || true",
        "UPLINK=$(esxcli network nic list | awk 'NR>2 && $5 == \"Up\" {print $1; exit}')",
        "if [ -n \"$UPLINK\" ]; then",
        "  echo \"Selected linked management uplink: $UPLINK\" >> $LOG",
        "  esxcli network vswitch standard uplink add --uplink-name=\"$UPLINK\" --vswitch-name=vSwitch0 >> $LOG 2>&1 || true",
        "  esxcli network ip interface set --interface-name=vmk0 --enabled=true >> $LOG 2>&1 || true",
        (
            "  esxcli network ip interface ipv4 set --interface-name=vmk0 "
            f"--ipv4={quote(spec.management_ip)} "
            f"--netmask={quote(spec.subnet_mask)} "
            "--type=static >> $LOG 2>&1 || true"
        ),
        "else",
        "  echo 'No linked physical NIC found for management network repair.' >> $LOG",
        "fi",
    ]
    if spec.enable_ssh:
        lines.append("vim-cmd hostsvc/enable_ssh")
        lines.append("vim-cmd hostsvc/start_ssh")
    if spec.disable_ipv6:
        lines.append("esxcli network ip set --ipv6-enabled=false || true")
    if spec.ntp_server:
        lines.append(f"esxcli system ntp set --server {quote(spec.ntp_server)} || true")
    lines.append("%end")
    return "\n".join(lines) + "\n"
